language: python

python:
  - 2.7
  - 3.4

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install python-pip openjdk-7-jdk
  - pip install --upgrade cython

script:
  - make
  - make tests

notifications:
  irc:
    channels:
      - chat.freenode.net#kivy-dev
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
